baseURL = 'https://ospens.github.io/react-roadmap/'
languageCode = 'ru'
title = 'Испытание багами'
theme = 'hugo-book'

[params]
    BookTheme = 'auto'
    BookSection = '*'

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
unsafe = true
